const $=id=>document.getElementById(id);const state={formats:[],type:"video"};
function log(m){const t=new Date().toLocaleTimeString("zh-TW",{hour12:false}),b=$("log");b.textContent=b.textContent==="尚未執行。"?"":b.textContent;b.textContent+=`[${t}] ${m}\n`;b.scrollTop=b.scrollHeight}
function status(m,c="idle"){const n=$("status");n.className=`status ${c}`;n.querySelector("span:last-child").textContent=m}
function videoId(v){const u=new URL(v);if(u.hostname==="youtu.be")return u.pathname.slice(1).split("/")[0];if(u.hostname.endsWith("youtube.com")){if(u.pathname==="/watch")return u.searchParams.get("v");const m=u.pathname.match(/^\/(?:shorts|embed|live)\/([^/?]+)/);if(m)return m[1]}return null}
function endpoint(path,p={}){const base=$("worker").value.trim().replace(/\/$/,"");if(!base)throw Error("請先在進階設定輸入 Cloudflare Worker 網址");const u=new URL(base+path);Object.entries(p).forEach(([k,v])=>u.searchParams.set(k,v));return u.href}
function numericQuality(f){const m=String(f.quality||"").match(/\d+/);return m?Number(m[0]):0}
function available(){return state.type==="video"?state.formats.filter(f=>f.kind==="影音合一"&&f.mimeType?.startsWith("video/")):state.formats.filter(f=>f.kind==="僅音訊"||f.mimeType?.startsWith("audio/"))}
function populate(){const list=available(),q=$("quality");q.replaceChildren();if(state.type==="video"){list.sort((a,b)=>numericQuality(b)-numericQuality(a));for(const f of list){const o=document.createElement("option");o.value=state.formats.indexOf(f);o.textContent=`${f.quality} · ${f.container.toUpperCase()} · 影音合一`;q.append(o)}}else{list.sort((a,b)=>(b.bitrate||0)-(a.bitrate||0));for(const f of list){const o=document.createElement("option");o.value=state.formats.indexOf(f);o.textContent=`${Math.round((f.bitrate||0)/1000)||"未知"} kbps · ${f.container.toUpperCase()} 來源`;q.append(o)}}const none=!list.length;$("download").disabled=none;$("formatNote").textContent=none?(state.type==="video"?"目前沒有解析到影音合一格式。高畫質常為影音分離，需下一版加入合併功能。":"目前沒有解析到可用音訊來源。"):(state.type==="video"?"下載結果會使用 YouTube 提供的影音合一串流，檔案以 MP4 名稱輸出。":"音訊來源會送至瀏覽器端轉檔流程。此 v2 介面已提供 MP3 位元率選擇，目前下載先保留來源音訊格式，MP3 實際轉碼將於加入 ffmpeg.wasm 後啟用。");updateButton()}
function updateButton(){const text=state.type==="video"?"下載 MP4":`下載音訊（${$("bitrate").value} kbps）`;$("download").querySelector("span").textContent=text}
async function analyze(){const b=$("analyze");try{b.disabled=true;status("正在取得 YouTube 播放器資料…","working");const id=videoId($("youtubeUrl").value.trim());if(!id)throw Error("這不是可辨識的 YouTube 網址");localStorage.setItem("workerUrl",$("worker").value.trim());log(`開始解析影片 ID：${id}`);const r=await fetch(endpoint("/youtube",{id}),{cache:"no-store"}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Worker 回傳 HTTP ${r.status}`);state.formats=Array.isArray(d.formats)?d.formats:[];$("title").textContent=d.title||`YouTube ${id}`;$("thumbnail").src=d.thumbnail||`https://i.ytimg.com/vi/${id}/hqdefault.jpg`;$("meta").textContent=`影片 ID：${id} · 共取得 ${state.formats.length} 個候選格式`;$("videoInfo").classList.remove("hidden");$("convertPanel").classList.remove("hidden");populate();if(!state.formats.length)throw Error(d.note||"目前沒有可直接使用的影音格式");status(`解析完成，共找到 ${state.formats.length} 個候選格式`,"success");log(`解析完成：${state.formats.length} 個候選格式`);$("convertPanel").scrollIntoView({behavior:"smooth",block:"start"})}catch(e){status(e.message,"error");log(`解析失敗：${e.message}`)}finally{b.disabled=false}}
async function download(){try{const i=Number($("quality").value),f=state.formats[i];if(!f)throw Error("沒有可下載的格式");status(`正在驗證 ${f.quality}…`,"working");const test=await fetch(endpoint("/media",{url:f.url}),{headers:{Range:"bytes=0-65535"},cache:"no-store"});if(![200,206].includes(test.status))throw Error(`媒體驗證失敗：HTTP ${test.status}`);await test.body?.cancel();const a=document.createElement("a");a.href=endpoint("/media",{url:f.url,download:"1",ext:state.type==="video"?"mp4":f.container||"m4a"});a.rel="noopener";document.body.append(a);a.click();a.remove();status("已將下載工作交給瀏覽器","success");log(`開始下載：${state.type} / ${f.quality} / ${f.container}`)}catch(e){status(e.message,"error");log(`下載失敗：${e.message}`)}}
$("analyze").onclick=analyze;$("download").onclick=download;$("youtubeUrl").onkeydown=e=>{if(e.key==="Enter")analyze()};$("clearLog").onclick=()=>$("log").textContent="尚未執行。";$("bitrate").onchange=updateButton;document.querySelectorAll(".type-option").forEach(btn=>btn.onclick=()=>{document.querySelectorAll(".type-option").forEach(x=>x.classList.remove("active"));btn.classList.add("active");state.type=btn.dataset.type;$("qualityGroup").classList.toggle("hidden",state.type!=="video");$("bitrateGroup").classList.toggle("hidden",state.type!=="audio");if(state.type==="audio")$("qualityGroup").classList.remove("hidden");populate()});$("worker").value=localStorage.getItem("workerUrl")||"";
