"use strict";
const $=id=>document.getElementById(id);
const state={formats:[],type:"video"};
function log(message){const time=new Date().toLocaleTimeString("zh-TW",{hour12:false});const box=$("log");if(box.textContent==="尚未執行。")box.textContent="";box.textContent+=`[${time}] ${message}
`;box.scrollTop=box.scrollHeight;}
function status(message,kind="idle"){const node=$("status");node.className=`status ${kind}`;node.querySelector("span:last-child").textContent=message;}
function videoId(value){try{const url=new URL(value.trim());const host=url.hostname.toLowerCase().replace(/^www\./,"");if(host==="youtu.be")return url.pathname.split("/").filter(Boolean)[0]||null;if(host==="youtube.com"||host==="m.youtube.com"||host==="music.youtube.com"){if(url.pathname==="/watch")return url.searchParams.get("v");const match=url.pathname.match(/^\/(?:shorts|embed|live)\/([^/?#]+)/);return match?match[1]:null;}return null;}catch{return null;}}
function endpoint(path,params={}){const base=$("worker").value.trim().replace(/\/$/,"");if(!base)throw Error("請先在進階設定輸入 Cloudflare Worker 網址。");const url=new URL(base+path);Object.entries(params).forEach(([key,value])=>url.searchParams.set(key,value));return url.href;}
function numericQuality(format){const match=String(format.quality||"").match(/\d+/);return match?Number(match[0]):0;}
function available(){return state.type==="video"?state.formats.filter(f=>f.kind==="影音合一"&&f.mimeType?.startsWith("video/")):state.formats.filter(f=>f.kind==="僅音訊"||f.mimeType?.startsWith("audio/"));}
function updateButton(){const selected=state.formats[Number($("quality").value)];const text=state.type==="video"?"下載 MP4":`下載 ${String(selected?.container||"音訊").toUpperCase()}`;$("download").querySelector("span").textContent=text;}
function populate(){const list=available(),select=$("quality");select.replaceChildren();if(state.type==="video")list.sort((a,b)=>numericQuality(b)-numericQuality(a)||(b.bitrate||0)-(a.bitrate||0));else list.sort((a,b)=>(b.bitrate||0)-(a.bitrate||0));for(const format of list){const option=document.createElement("option");option.value=state.formats.indexOf(format);const rate=format.bitrate?`${Math.round(format.bitrate/1000)} kbps`:"位元率未知";option.textContent=state.type==="video"?`${format.quality} · ${format.container.toUpperCase()} · 影音合一`:`${rate} · ${format.container.toUpperCase()} · ${format.codec||"未知編碼"}`;select.append(option);}const empty=!list.length;$("download").disabled=empty;$("formatNote").textContent=empty?(state.type==="video"?"目前沒有可直接使用的影音合一格式。1080p 以上通常需要 FFmpeg 合併。":"目前沒有可直接使用的音訊格式。"):(state.type==="video"?"下載使用 YouTube 提供的影音合一串流。":"下載保留 YouTube 提供的原始音訊容器，不會偽裝成 MP3。");updateButton();}
async function analyze(){const button=$("analyze");try{button.disabled=true;status("正在解析 YouTube 播放器資料…","working");const id=videoId($("youtubeUrl").value);if(!id||!/^[A-Za-z0-9_-]{11}$/.test(id))throw Error("這不是可辨識的 YouTube 網址。");localStorage.setItem("workerUrl",$("worker").value.trim());log(`開始解析影片 ID：${id}`);const response=await fetch(endpoint("/youtube",{id}),{cache:"no-store"});const data=await response.json().catch(()=>({}));if(Array.isArray(data.steps))data.steps.forEach(log);if(!response.ok)throw Error(data.error||`Worker 回傳 HTTP ${response.status}。`);state.formats=Array.isArray(data.formats)?data.formats:[];$("title").textContent=data.title||`YouTube ${id}`;$("thumbnail").src=data.thumbnail||`https://i.ytimg.com/vi/${id}/hqdefault.jpg`;$("meta").textContent=`影片 ID：${id} · 來源：${data.source||"未知"} · 可用格式：${state.formats.length} 個`;$("videoInfo").classList.remove("hidden");$("convertPanel").classList.remove("hidden");populate();if(!state.formats.length)throw Error(data.note||"目前沒有可直接使用的影音格式。");status(`解析完成，共找到「${state.formats.length}」個可用格式。`,"success");log(`解析完成，共找到「${state.formats.length}」個可用格式。`);$("convertPanel").scrollIntoView({behavior:"smooth",block:"start"});}catch(error){status(error.message,"error");log(`解析失敗：${error.message}`);}finally{button.disabled=false;}}
async function download(){try{const format=state.formats[Number($("quality").value)];if(!format)throw Error("沒有可下載的格式。");status(`正在驗證「${format.quality}」格式…`,"working");const test=await fetch(endpoint("/media",{url:format.url}),{headers:{Range:"bytes=0-65535"},cache:"no-store"});if(![200,206].includes(test.status))throw Error(`媒體驗證失敗：HTTP ${test.status}。`);await test.body?.cancel();const anchor=document.createElement("a");anchor.href=endpoint("/media",{url:format.url,download:"1",ext:state.type==="video"?"mp4":format.container||"m4a"});anchor.rel="noopener";document.body.append(anchor);anchor.click();anchor.remove();status("已將下載工作交給瀏覽器。","success");log(`開始下載：${state.type}／${format.quality}／${format.container}。`);}catch(error){status(error.message,"error");log(`下載失敗：${error.message}`);}}
$("analyze").onclick=analyze;$("download").onclick=download;$("youtubeUrl").onkeydown=event=>{if(event.key==="Enter")analyze();};$("clearLog").onclick=()=>$("log").textContent="尚未執行。";$("quality").onchange=updateButton;document.querySelectorAll(".type-option").forEach(button=>button.onclick=()=>{document.querySelectorAll(".type-option").forEach(item=>item.classList.remove("active"));button.classList.add("active");state.type=button.dataset.type;populate();});$("worker").value=localStorage.getItem("workerUrl")||"";